export const generators = [
  {
    name: "universal-agent",
    description: "🤖 Universal Agent Skills - Configure AI agents with SKILL.md & AGENTS.md standards",
    category: "AI Agents",
    featured: true,
    icon: "🌌",
    prompts: [
      {
        type: "input",
        name: "projectName",
        message: "Project Name",
        default: "my-project",
      },
      {
        type: "input",
        name: "destination",
        message: "Destination path",
        default: "temps/",
      },
      {
        type: "skill-selector",
        name: "skills",
        message: "Select Skills from antigravity-awesome-skills",
        default: [],
      },
      {
        type: "agent-selector",
        name: "agents",
        message: "Select Target Agents",
        default: ["antigravity", "cursor"],
      },
      {
        type: "checkbox",
        name: "options",
        message: "Additional Options",
        choices: [
          { name: "Clone skills repository", value: "clone-skills" },
          { name: "Generate setup script", value: "setup-script" },
          { name: "Run setup automatically (OS based)", value: "run-setup" },
          { name: "Create symlinks (for Trae)", value: "symlinks" },
          { name: "Initialize Git repository", value: "git-init" },
        ],
        default: ["clone-skills", "setup-script"],
      },
    ],
  },
  {
    name: "electron-float",
    description: "Scaffold an Electron app with Float DevTools",
    prompts: [
      {
        type: "input",
        name: "name",
        message: "Application name",
        default: "float-devtools-app",
      },
      {
        type: "input",
        name: "destination",
        message: "Destination path",
        default: ".",
      },
    ],
  },
  {
    name: "tron-mini",
    description: "Scaffold a minimal Tron UI plugin",
    prompts: [
      {
        type: "input",
        name: "destBase",
        message: "Destination base path",
        default: "apps",
      },
      {
        type: "input",
        name: "pluginSlug",
        message: "Workspace folder name",
        default: "tron-mini",
      },
      {
        type: "input",
        name: "pluginName",
        message: "Plugin display name",
        default: "Hello Tron Mini",
      },
      {
        type: "input",
        name: "version",
        message: "Plugin version",
        default: "0.1.0",
      },
      {
        type: "input",
        name: "port",
        message: "Dev server port",
        default: "3002",
      },
      {
        type: "input",
        name: "previewPort",
        message: "Preview server port",
        default: "3001",
      },
    ],
  },
  {
    name: "agent-rules",
    description: "Generate AI agent rule files",
    prompts: [
      {
        type: "input",
        name: "destination",
        message: "Destination project path",
        default: ".",
      },
      {
        type: "checkbox",
        name: "agents",
        message: "Which agent rules do you want to generate?",
        choices: [
          { name: "Agents (Base Rules)", value: "AGENTS" },
          { name: "Trae", value: "TRAE" },
          { name: "Claude", value: "CLAUDE" },
          { name: "Gemini", value: "GEMINI" },
          { name: "Qwen", value: "QWEN" },
          { name: "Cline", value: "CLINE" },
          { name: "Cursor", value: "CURSOR" },
          { name: "Windsurf", value: "WINDSURF" },
          { name: "Copilot", value: "COPILOT" },
        ],
      },
    ],
  },
  {
    name: "app-scaffold",
    description: "Scaffold a new application with Counter Demo",
    prompts: [
      {
        type: "list",
        name: "frontend",
        message: "Select Frontend Framework",
        choices: [
          { name: "Next.js 15", value: "nextjs-15" },
          { name: "Next.js 16", value: "nextjs-16" },
          { name: "Vite + React 19", value: "vite-react-9" },
          { name: "TanStack Start", value: "tanstack-start" },
          { name: "Vue 3", value: "vue3" },
          { name: "Nuxt 4", value: "nuxt4" },
          { name: "RN Reusables (Expo Nativewind)", value: "rnr-expo" },
          { name: "RN Reusables (Expo Uniwind)", value: "rnr-expo-uniwind" },
          { name: "Turbo Uniwind", value: "turbo-uniwind" },
        ],
      },
      {
        type: "checkbox",
        name: "ui",
        message: "Select UI / CSS Stack",
        choices: [
          { name: "Shadcn UI / Tailwind", value: "shadcn" },
          { name: "Tailwind CSS Only", value: "tailwind" },
          { name: "Hero UI", value: "heroui" },
        ],
      },
      {
        type: "list",
        name: "packageManager",
        message: "Select Package Manager",
        choices: [
          { name: "pnpm", value: "pnpm" },
          { name: "npm", value: "npm" },
          { name: "yarn", value: "yarn" },
          { name: "bun", value: "bun" },
        ],
        default: { name: "pnpm", value: "pnpm" },
      },
      {
        type: "input",
        name: "name",
        message: "Application Name",
        default: "my-app",
      },
      {
        type: "input",
        name: "dest",
        message: "Destination directory",
        default: "apps",
      },
    ],
  },
];
